### ISSUE TITLE
Not quite working in FF 41 and above

### ISSUE THREAD

**Issue by buttercookie42** [miraks/ShareToBottom#1]
Hi, for some reasons, starting from Firefox 41, this add-on isn't properly working anymore - after launching Firefox, the share menu entries are still on top.
However, if I then go into the add-on manager and first deactivate and then reactivate this add-on, it's working again until the next restart of Firefox. So it doesn't seem completely broken, only that something goes wrong during Firefox start up.

**Comment by miraks** [comment]
Hi. There is right now an issue with auto-signing android-only firefox addons (https://bugzilla.mozilla.org/show_bug.cgi?id=1185789). I assume that's the reason, but I'll check it out.

**Comment by buttercookie42** [comment]
No, I don't think it's about signing, because that still isn't enforced - and even if it would be, all that would do would be to completely deactivate your add-on.
To clarify, your add-on remains activated all the time, only for some reason, during browser start-up the process of hooking into the browser window and manipulating the menu somehow fails - if I then later retry by forcing your add-on deactivated and activated again, it's suddenly working again.

I assume something changed in the process of Firefox start up, which means some component now isn't quite ready when your add-on wants to manipulate the menu, hence it's not working.

If you want to, I might later try a mozregression run to see if I can pinpoint the change that broke your add-on.

**Comment by miraks** [comment]
You were right. I browsed FF sources and found that `UIReady` event is now fired before the context menu initialization. I added workaround for this case and will publish a new version of soon.

**Comment by buttercookie42** [comment]
Thank you very much.
