### ISSUE TITLE
Broken/incompatible starting with Firefox Quantum

### ISSUE THREAD

**Issue by darklajid** [miraks/ShareToBottom#2]
Hey.

First of all let me thank you for this addon: It was making my life a tiny bit better every day, for quite some time.

Unfortunately - it's not compatible with the latest Firefox anymore. Is there no way around this (i.e. is this a problem similar to lots of broken addons: This cannot be done in a web extension) or is it possible to make this work somehow?

**Comment by miraks** [comment]
Hello.

Thanks :)
No, unfortunately it isn't possible to migrate this addon to web extensions API. But if it ever became possible I'd definitely port it. I'll add notice to the readme and to the description on addon page.
